export const products = [
  {
    id: '1',
    name: 'Groot',
    price: 15,
    photoOne: '/groot1.png',
    photoTwo: '/groot2.png',
  },
  {
    id: '2',
    name: 'Captain Marvel',
    price: 15,
    photoOne: '/captain_marvel1.png',
    photoTwo: '/captain_marvel2.png',
  },
  {
    id: '3',
    name: 'Gambit',
    price: 15,
    photoOne: '/gambit1.png',
    photoTwo: '/gambit2.png',
  },
  {
    id: '4',
    name: 'Harley Quinn',
    price: 15,
    photoOne: '/harley1.png',
    photoTwo: '/harley2.png',
  },
  {
    id: '5',
    name: 'Superman',
    price: 15,
    photoOne: '/superman1.png',
    photoTwo: '/superman2.png',
  },
  {
    id: '6',
    name: 'Joker',
    price: 15,
    photoOne: '/joker1.png',
    photoTwo: '/joker2.png',
  },
  {
    id: '7',
    name: 'Spider-Man',
    price: 15,
    photoOne: '/spiderman1.png',
    photoTwo: '/spiderman2.png',
  },
  {
    id: '8',
    name: 'Wonder Woman',
    price: 15,
    photoOne: '/wonderwoman1.png',
    photoTwo: '/wonderwoman2.png',
  },
  {
    id: '9',
    name: 'Iron Man',
    price: 15,
    photoOne: '/ironman1.png',
    photoTwo: '/ironmanr2.png',
  },
];
